#!/bin/bash

# Check if the correct number of arguments is given
if [ "$#" -ne 3 ]; then
    echo "Usage: kube <environment> <cluster> <namespace>"
    exit 1
fi

# Assign arguments to variables
environment=$1
color=$2
namespace=$3

# Launch k9s with the specified context and namespace
k9s -c <insert the context> -n <insert the namespace> -c pod
